defaults:
  - _self_
  - vector_db: redis # Options: redis, chroma, faiss
  - embedding_model: nomic   # Options: nomic, all-MiniLM-L6-v2, multi-qa-MiniLM-L6-cos-v1
  - llm: ollama  # Options: ollama, option 2
  - chunking  # Loads chunking.yaml
  - data # Loads data.yaml

# Data directory
data:
  pdf_dir: "/Users/lesrene/Desktop/DS4300/RagIngestAndSearch/data/ds4300 notes" 

# Paths to scripts
scripts:
  injest: "injest_hydra.py"
  search: "search_hydra.py"