defaults:
  - _self_
  - vector_db: redis # Options: redis, chroma, faiss
  - embedding_model: nomic   # Options: nomic, all-Mini, all-mpnet
  - llm: mistral  # Options: mistral, llama2
  - prompts_dir # Loads prompts_dir.yaml
  - chunking  # Loads chunking.yaml
  - data_dir # Loads data_dir.yaml

# Paths to scripts
scripts:
  #injest: "ingest_hydra.py"
  injest: "src/ingest_hydra.py"
  #search: "search_hydra.py"
  search: "src/search_hydra.py"
